"""
Embedding-based labeling for GDELT articles.

This module provides semantic/embedding-based classification of Swedish news articles
using sentence transformers and cosine similarity, replacing the keyword-matching approach
with something more robust and semantically aware.

Templates and keywords can be dynamically loaded from JSON files generated by generate_templates.py,
or fall back to hardcoded defaults.
"""

import json
import logging
import sys
from pathlib import Path
from typing import Dict, Tuple, List
import numpy as np
import string
import re

from sentence_transformers import SentenceTransformer
import torch

# Try to import Swedish stemmer and stopwords
try:
    from nltk.stem.snowball import SnowballStemmer
    from nltk.corpus import stopwords
    import nltk
    
    # Download required NLTK data if not present
    try:
        nltk.data.find('corpora/stopwords')
    except LookupError:
        nltk.download('stopwords', quiet=True)
    
    SWEDISH_STEMMER = SnowballStemmer('swedish')
    SWEDISH_STOPWORDS = set(stopwords.words('swedish'))
    HAS_NLTK = True
except ImportError:
    HAS_NLTK = False
    SWEDISH_STEMMER = None
    SWEDISH_STOPWORDS = set()
    logger_temp = logging.getLogger(__name__)
    logger_temp.warning("NLTK not available; Swedish text preprocessing will be basic")

# Add project root to path
PROJECT_ROOT = Path(__file__).resolve().parents[2]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

logger = logging.getLogger(__name__)

# Global model cache
_model = None
_signal_embeddings = None
_loaded_templates = None
_loaded_keywords = None


def preprocess_swedish_text(text: str, remove_stopwords: bool = False, stem: bool = True) -> str:
    """
    Preprocess Swedish text: remove punctuation, lowercase, optionally remove stopwords and stem.
    
    Args:
        text: Input text to preprocess
        remove_stopwords: If True, remove Swedish stopwords
        stem: If True, apply Swedish stemming
        
    Returns:
        Preprocessed text as space-separated tokens
    """
    if not text:
        return ""
    
    # Lowercase
    text = text.lower()
    
    # Remove punctuation (keep only alphanumeric and spaces)
    text = text.translate(str.maketrans('', '', string.punctuation))
    
    # Remove extra whitespace and split
    tokens = text.split()
    
    # Remove stopwords if requested and NLTK available
    if remove_stopwords and HAS_NLTK:
        tokens = [t for t in tokens if t not in SWEDISH_STOPWORDS and len(t) > 1]
    
    # Apply stemming if requested and NLTK available
    if stem and HAS_NLTK:
        tokens = [SWEDISH_STEMMER.stem(t) for t in tokens]
    
    return ' '.join(tokens)


def extract_keywords_with_encoder(text: str, max_keywords: int = 50, 
                                   ngram_range: Tuple[int, int] = (1, 2)) -> Dict[str, float]:
    """
    Extract keywords from preprocessed text using TF-IDF scoring.
    
    Args:
        text: Preprocessed text (ideally from preprocess_swedish_text)
        max_keywords: Maximum number of keywords to extract
        ngram_range: Tuple of (min_n, max_n) for n-gram extraction
        
    Returns:
        Dict mapping keyword to relevance score (0 to 1)
    """
    try:
        from sklearn.feature_extraction.text import TfidfVectorizer
    except ImportError:
        logger.warning("scikit-learn not available; returning empty keywords")
        return {}
    
    # For single document, use simple term frequency instead of TF-IDF
    tokens = text.split()
    if not tokens:
        return {}
    
    # Count token frequencies
    token_freq = {}
    for token in tokens:
        token_freq[token] = token_freq.get(token, 0) + 1
    
    # Normalize by total count
    total = len(tokens)
    keyword_scores = {
        token: count / total 
        for token, count in token_freq.items()
    }
    
    # Sort by frequency and return top N
    sorted_keywords = sorted(keyword_scores.items(), key=lambda x: x[1], reverse=True)
    return dict(sorted_keywords[:max_keywords])


# Global model cache
_model = None
_signal_embeddings = None
_loaded_templates = None
_loaded_keywords = None


# Define semantic templates for each signal category
# Using REAL excerpts from GDELT articles for accurate semantic matching
SIGNAL_TEMPLATES = {
    "emergencies": [
        "Villabrand i Kramfors – räddningstjänsten larmad",
        "Brand i flerfamiljshus – boende evakueras",
        "Industribrand utanför Borlänge – kraftig rökutveckling",
        "Lägenhetsbrand i Malmö – en till sjukhus",
        "Skogsbrand sprider sig – flera enheter på väg",
        "Brand i parkeringsgarage – rökdykare arbetar på plats",
        "Explosion i trapphus – avspärrningar upprättade",
        "Misstänkt farligt föremål – Nationella bombskyddet inkopplat",
        "Gasläcka i centrum – kvarter utryms",
        "Kemikalieutsläpp vid industriområde – sanering pågår",
        "Räddningsinsats i vattnet – person saknas",
        "Stor räddningsinsats efter drunkningslarm",
        "Helikopter kallas in till fjällräddning",
        "Rasrisk vid vägskärning – område spärras av",
        "Byggnadsställning kollapsade – flera skadade",
        "Tak rasade in efter snötyngd",
        "Tågolycka – räddningstjänst och ambulans larmade",
        "Bil körde in i folkmassa – flera skadade",
        "Masskrock på E4 – totalstopp i trafiken",
        "Bussolycka – passagerare skadade",
        "Båt i nöd – sjöräddningen larmad",
        "Flygincident på landningsbanan – räddningsfordon ute",
        "Strömavbrott slår ut samhällen – tusentals utan el",
        "Vattenläcka orsakar översvämning i fastighet",
        "Översvämningar hotar – kommunen öppnar trygghetspunkt",
        "Skyfall drar in – flera larm om översvämmade källare",
        "Stormfällda träd – räddningstjänsten hanterar många larm",
        "Ovädret drar fram – stora materiella skador rapporteras",
        "SMHI varnar för mycket hårda vindbyar",
        "SMHI utvidgar varningen – klass 2-varning i flera län",
        "Lavinfara i fjällen – uppmaning att undvika branta sluttningar",
        "Jordskred misstänks – boende evakueras",
        "Jordbävning registrerad – skador rapporteras",
        "Nödläge utlyst efter naturkatastrof",
        "Akut vattenbrist – bevattningsförbud införs",
        "Flera larm om höga smällar – polis och räddningstjänst utreder",
        "Räddningsledare: Insatsen kan pågå hela natten",
        "SOS Alarm: Ovanligt många samtal under kvällen",
    ],

    "crime": [
        "Misstänkt mord – stor polisinsats i området",
        "Mordförsök – man anhållen efter knivhugg",
        "Skottlossning i bostadsområde – ingen gripen",
        "Skott avlossade mot lägenhet – tekniker på plats",
        "Grov misshandel – flera personer gripna",
        "Rån mot butik – hotade personal med tillhygge",
        "Bankomatrån – polis söker vittnen",
        "Inbrottsvåg i villaområde – boende uppmanas låsa",
        "Stöld ur bil – flera anmälningar samma natt",
        "Bedrägerier via sms – polisen varnar för ny metod",
        "Telefonbedrägeri mot äldre – flera drabbade",
        "Narkotikabrott – stora beslag vid tillslag",
        "Knarkgömma hittad – flera kilo i beslag",
        "Gängrelaterad konflikt – ökad polisiär närvaro",
        "Sprängning vid port – Nationella bombskyddet larmades",
        "Detonation vid restaurang – avspärrningar på plats",
        "Misstänkt mordbrand – brandplatsundersökning inledd",
        "Polisen: Unga rekryteras till mordbrand och sprängningar",
        "Våldtäkt utreds – misstänkt gripen",
        "Fängelse för våldtäkt i park i Örebro",
        "Åtal väckt för grovt brott – nekar till anklagelserna",
        "Häktad misstänkt – åklagaren begär fortsatt häktning",
        "Rättegång inleds – åtal för dubbelmord",
        "Dom faller i uppmärksammat mål",
        "Säpo-tillslag – misstänkt brott mot rikets säkerhet",
        "Hot mot tjänsteman – utredning pågår",
        "Olovlig påverkan – vittnen pressade enligt polis",
        "Polisen söker efter hotfull man – insats med hundpatrull",
        "Misstänkt kidnappningsförsök – polis utreder",
        "Efterlyst person gripen efter biljakt",
        "Biljakt slutade i krasch – två anhållna",
        "Vapenbrott – pistol hittad vid visitation",
        "Knivlagen: flera omhändertagna vid kontroll",
        "Ekobrott – misstänkta bokföringsbrott utreds",
        "IT-attack mot företag – cyberbrottsenhet inkopplad",
        "Pengatvätt misstänks – flera konton frysta",
        "Vittnen söks – polisen går ut med signalement",
        "Förundersökning inledd – brottsrubriceringen skärps",
    ],

    "festivals": [
        "Festivalen invigs i centrala stan – tusentals väntas",
        "Kulturfestival lockar publik – fullsatta gator",
        "Stadsfest i helgen – program och tider klara",
        "Valborgsfirande med majbrasa – räddningstjänsten varnar",
        "Nationaldagsfirande med tal och musik",
        "Midsommarfirande i parken – dans runt stången",
        "Julmarknad öppnar – hantverk och lokala smaker",
        "Prideparad genom innerstan – trafikomläggningar planeras",
        "Karneval med parad – arrangören räknar med rekord",
        "Konsert på torget – artist uppträder i kväll",
        "Turnépremiär i Stockholm – biljetter slutsålda",
        "Musikfestival presenterar nya akter",
        "Ny konstutställning öppnar på museet",
        "Vernissage i helgen – fri entré",
        "Teaterpremiär på stadsteatern",
        "Operakväll med gästsolist",
        "Standupkväll på klubben – flera komiker på scen",
        "Dansföreställning får lovord – extra föreställningar släpps",
        "Filmfestival startar – internationella gäster på plats",
        "Bokmässa öppnar – författare möter läsare",
        "Kulturpris delas ut under galan",
        "Gala med prisutdelning – kändistäta röda mattan",
        "Matfestival i hamnen – food trucks och provsmakning",
        "Öl- och matmässa lockar besökare",
        "Hantverksmässa i mässhallen – utställare från hela landet",
        "Marknad på torget – lokala producenter deltar",
        "Loppisrunda i kommunen – kartan släppt",
        "Invigning av ny scen – kommunen satsar på kultur",
        "Allsångskväll vid sjön – fri entré",
        "Fackeltåg planeras – arrangören uppmanar till lugn",
        "Religiös högtid firas – samling i kyrkan",
        "Studentfirande – utspring och kortege",
        "Nyårsfirande – fyrverkeriförbud på flera håll",
        "Kulturprogrammet släppt – workshops och familjeaktiviteter",
        "Publikrekord när festivalen återvände",
        "Evenemanget ställs in – säkerhetsläget avgörande",
    ],

    "transportation": [
        "Trafikverket varnar: Risk för ishalka på E4",
        "Tågtrafiken står stilla efter signalfel",
        "Stopp i tågtrafiken – resenärer uppmanas söka alternativ",
        "Förseningar på pendeltågen – tekniskt fel",
        "Banarbete orsakar inställda avgångar",
        "Rivningsarbete stänger av väg – omledning via centrum",
        "Olycka på E6 – långa köer i båda riktningar",
        "Masskrock på motorvägen – flera fordon inblandade",
        "Lastbil i diket – bärgning pågår",
        "Halkolyckor rapporteras – flera vägar avstängda",
        "Trafikstockning efter olycka – räddningstjänst på plats",
        "Vägen avstängd efter rasrisk",
        "Bro stängs för reparation – trafiken leds om",
        "Vägarbete påverkar framkomligheten i rusningen",
        "Busslinje inställd – chaufförsbrist uppges",
        "Störningar i kollektivtrafiken – flera linjer drabbade",
        "Tunnelbanan stoppad – strömlöst på sträckan",
        "Spårvagn ur spår – trafiken omledd",
        "Färjor inställda på grund av hård vind",
        "Flygförseningar på Arlanda – köer till säkerhetskontrollen",
        "Inställda flyg – dimma och låg sikt",
        "Landningsproblem – flyg tvingas vända",
        "Varning för drivbildning – fjällvägar kan stängas",
        "SMHI-varning påverkar trafiken – halka väntas",
        "Trafikolycka i tunnel – totalstopp",
        "Tekniskt fel i signalsystemet – omfattande förseningar",
        "Vagnfel stoppar tåg – ersättningsbussar sätts in",
        "Kabelbrott påverkar tågtrafiken i flera timmar",
        "Kökaos efter avstängning – resenärer fast",
        "Trängsel i rusning – extra avgångar sätts in",
        "Ny tidtabell införs – ändrade avgångstider",
        "Strejkvarsel kan stoppa trafiken",
        "Stängd hållplats – säkerhetsarbete pågår",
        "Omdirigeringar i city – vägar spärras av",
        "Reseavrådan: Undvik onödiga resor i ovädret",
        "Trafikinfo: Långa restider på flera leder",
    ],

    "weather_temp": [
        "Mildluft drar in – temperaturerna stiger snabbt",
        "Kallfront på väg – kraftigt temperaturfall väntas",
        "Nattfrost i stora delar av landet",
        "SMHI utfärdar varning för sträng kyla",
        "Bistert kallt i norr – minusgrader dygnet runt",
        "Värmebölja i södra Sverige – varmaste dagen hittills",
        "Högsommarvärme i april – ovanligt varmt",
        "Köldknäpp slår till – risk för is på vägarna",
        "Kyla och blåst ger extrem vindkyleeffekt",
        "Tropiska nätter väntas – svårt att sova",
        "Värmen pressar elnätet – hög belastning",
        "Temperaturrekord noteras – nytt dygnsrekord",
        "Ovanligt varmt för årstiden – meteorolog: ”anmärkningsvärt”",
        "Ovanligt kallt för säsongen – flera rekord hotas",
        "Snabba väderskiften – från plusgrader till minus",
        "Vårvärme ersätts av vinterkänsla",
        "Hetluft i staden – varning för hög UV-nivå",
        "Soligt men kallt – stora skillnader mellan dag och natt",
        "Risk för värmestress – rådet till äldre och sjuka",
        "Kyla drabbar vattenledningar – risk för frysskador",
        "Frostvarning för jordbruket – odlare oroade",
        "Värmevarning utfärdad – SMHI uppmanar till försiktighet",
        "Temperaturen sjunker under natten – risk för halka",
        "Temperatursvängningar ger besvär för pollenallergiker",
        "Långvarig kyla – kommuner öppnar värmestugor",
        "Långvarig värme – eldningsförbud kan bli aktuellt",
        "Kallaste natten hittills – flera stationer under -20",
        "Varmaste dagen på året – prognosen visar 30 grader",
        "Vädret slår om – svalare luft strömmar in",
        "Heta dagar fortsätter – ingen lättnad i sikte",
        "Isbildning på sjöar – varning för svaga isar",
        "Snösmältning i värmen – höga flöden i vattendrag",
        "Meteorologen: ”Kraftig temperaturskillnad mellan landsdelarna”",
        "Vädervarning: Extrem kyla i kombination med vind",
        "Vädervarning: Mycket höga temperaturer lokalt",
        "Klimatindikator: ovanligt varm månad enligt preliminära data",
    ],

    "weather_wet": [
        "SMHI varnar för kraftigt snöfall",
        "Snöoväder drar in – risk för drivbildning",
        "Blötsnö och halka – varning utfärdad",
        "Stormvarning – mycket hårda vindbyar väntas",
        "Höststorm på väg – träd kan falla",
        "Kuling över kusten – färjetrafik påverkas",
        "Skyfall över staden – översvämningar på flera håll",
        "Kraftigt regn väntas – risk för översvämmade vägar",
        "Översvämningsrisk längs åar – höga flöden",
        "Vattennivåerna stiger – kommuner förbereder sandsäckar",
        "Hagel och åska – lokalt kraftiga skurar",
        "Åskoväder – risk för blixtnedslag och strömavbrott",
        "Slemmiga vägar efter regn – ökad olycksrisk",
        "Underkylt regn – mycket stor halkrisk",
        "Snöblandat regn i söder – besvärligt väglag",
        "Snöstorm – sikten kan bli mycket dålig",
        "Tät dimma – låg sikt på vägar och flygplatser",
        "Vindvarning i flera län – takpannor kan lossna",
        "Stormen drar fram – omfattande skador rapporteras",
        "Nederbörden tilltar – varning för höga vattenflöden",
        "Extrem nederbörd – räddningstjänsten får många larm",
        "Smältvatten och regn – risk för ras och skred",
        "Vinterväglag – plogning pågår dygnet runt",
        "Halka på broar – varning till trafikanter",
        "Snöfall över natten – skolskjutsar påverkas",
        "Regnoväder stannar kvar – fortsatt blött i flera dagar",
        "Kustvarning: Höga vågor och risk för överspolning",
        "Blixtnedslag slog ut el – många utan ström",
        "Nedfallna träd efter storm – flera vägar blockerade",
        "SMHI uppgraderar varningen – kraftigare vindar än väntat",
        "Väderläget förvärras – klass 2-varning utvidgas",
        "Högsta flödena på år – översvämningar i källare",
        "Vattenskador i bostäder – försäkringsbolag får in många ärenden",
        "Slask och plusgrader – risk för vattenplaning",
        "Snörök på fjällvägar – kraftigt nedsatt sikt",
        "Meteorologen: ”Räkna med intensiva skurar i eftermiddag”",
        "Vädervarning: Mycket stora regnmängder lokalt",
    ],

    "sports": [
        "Allsvenskan: Hemmalaget tog tre poäng",
        "Superettan: Sen kvittering räddade poäng",
        "SHL: Målvakten storspelade i segern",
        "Hockeyallsvenskan: Derbyt slutade med bortaseger",
        "Damallsvenskan: Nyförvärvet avgjorde direkt",
        "Svenska Cupen: Skrällag vidare efter straffar",
        "Champions League: Svensk lagkapten hyllas efter avancemang",
        "Europa League: Tuff bortamatch väntar",
        "VM-kval: Förbundskaptenen tar ut truppen",
        "EM: Sverige vidare till kvartsfinal",
        "OS: Svensk medalj efter dramatisk final",
        "Friidrott: Svenskt rekord på 800 meter",
        "Skidor: Pallplats i världscupen",
        "Skidskytte: Full pott i stående – klättrade i totalen",
        "Tennis: Svensken utslagen i åttondelen",
        "Handboll: Sverige vände och vann i slutminuterna",
        "Basket: Storseger hemma – klättrar i tabellen",
        "Fotboll: Tränaren får sparken efter förlustsvit",
        "Fotboll: Skada oroar inför toppmötet",
        "Hockey: Avstängning efter tackling – disciplinnämnden beslutade",
        "Matchen avbröts efter läktarstök",
        "Publikrekord på arenan – ”magisk stämning”",
        "Derbyhetta – polisen laddar inför matchen",
        "Övergång: Stjärnan klar för ny klubb",
        "Kontraktet förlängs – nyckelspelare stannar",
        "Lottningen klar – så spelas slutspelet",
        "Tabelläget: Viktig seger i bottenstriden",
        "Guldstrid: Två lag gör upp i sista omgången",
        "Träningsmatch: Målfest inför säsongsstart",
        "Säsongspremiär i helgen – förväntningarna stora",
        "Skadeläget: Flera borta – juniorer kallas upp",
        "Domslut i fokus – klubben rasar mot beslutet",
        "Straffdrama avgjorde – målvakten blev hjälte",
        "Formkurvan pekar uppåt – tredje raka segern",
        "Förlusten svider – ”vi måste höja oss”",
        "Presskonferens efter matchen – tränaren summerar",
    ],

    "economics": [
        "Börsen faller efter räntebesked",
        "Stockholmsbörsen stiger – banksektorn lyfter",
        "Kronan stärks mot euron",
        "Kronan försvagas – importen kan bli dyrare",
        "Inflationen sjunker enligt ny statistik",
        "Inflationen stiger – matpriserna driver upp",
        "Riksbanken lämnar räntan oförändrad",
        "Riksbanken höjer styrräntan",
        "Riksbanken sänker räntan – lättnad för bolånetagare",
        "Bolåneräntor justeras – banken ändrar villkoren",
        "Elpriserna stiger kraftigt – nya pristoppar",
        "Elpriserna faller – mildare väder påverkar",
        "Varsel på industriföretag – hundratals berörs",
        "Företag i konkurs – anställda drabbas",
        "Arbetslösheten ökar – fler inskrivna hos Arbetsförmedlingen",
        "Sysselsättningen stiger – fler i arbete",
        "BNP ökade mer än väntat",
        "BNP sjunker – ekonomin bromsar in",
        "Ny prognos: Lågkonjunkturen biter sig fast",
        "Konjunkturinstitutet: återhämtningen dröjer",
        "Konsumentförtroendet faller – hushållen pessimistiska",
        "Hushållens köpkraft pressas av priserna",
        "Löneavtal klart – så mycket höjs lönerna",
        "Strejkhot i avtalsrörelsen – parterna oense",
        "Företagsrapport: vinsten rasar",
        "Företagsrapport: starkare resultat än väntat",
        "Kraftig börsvolatilitet – oron ökar",
        "Bostadspriserna stiger enligt ny mätning",
        "Bostadspriserna faller – färre affärer",
        "Hyreshöjningar beslutade – så påverkas hushållen",
        "Matpriserna fortsätter upp – kedjorna försvarar sig",
        "Statistik: byggandet minskar – färre nya bostäder",
        "Exporten ökar – industrin går starkt",
        "Kreditförluster befaras – banker höjer reserveringar",
        "Skatteförändring föreslås – påverkar företag och privatpersoner",
        "Finansministern: ”vi ser en tydlig avmattning”",
    ],

    "politics": [
        "Regeringen presenterar nytt lagförslag",
        "Riksdagen röstar om budgeten",
        "Misstroendeomröstning väcks – oppositionen kräver besked",
        "Statsministern kommenterar kritiken",
        "Ministern avgår efter avslöjande",
        "Ny minister utses – regeringen gör rokad",
        "Partiledardebatt i riksdagen – skarpa ordväxlingar",
        "Utskottsförhör om hanteringen – myndighetschef kallas",
        "Regeringen tillsätter utredning",
        "Utredning föreslår skärpta regler",
        "Remissrunda inleds – flera myndigheter svarar",
        "Proposition lämnas till riksdagen",
        "Oppositionen lägger misstroendevotum",
        "Koalitionsförhandlingar fortsätter – besked väntas",
        "Nytt samarbete mellan partierna",
        "Valrörelsen trappas upp – nya utspel",
        "Valdatum fastställs – partierna laddar",
        "Kommunfullmäktige fattar beslut om skattehöjning",
        "Regionen antar ny vårdplan – kritiken växer",
        "EU-förhandlingar i slutfas – Sverige tar ställning",
        "EU-beslut påverkar svenska regler",
        "NATO-fråga debatteras – splittring mellan partier",
        "Säkerhetspolitisk presskonferens – nya besked",
        "Utrikesministern kallar upp ambassadör",
        "Diplomatisk konflikt – skarpt uttalande från regeringen",
        "Sanktioner diskuteras – EU enas om paket",
        "Protester mot regeringen – demonstration i huvudstaden",
        "Polisen uppskattar antalet demonstranter",
        "Lagändring om migration föreslås",
        "Skärpta straff föreslås – ny kriminalpolitik",
        "Klimatpaket presenteras – kritik från oppositionen",
        "Regeringen vill ändra skatteregler – så påverkas hushåll",
        "Budgetförslag läckt – partierna reagerar",
        "Talman kallar till extra överläggningar",
        "Statsråd: ”vi behöver agera skyndsamt”",
        "Myndighet får nytt uppdrag – regeringsbeslut i dag",
    ],
}


def load_signal_templates(templates_file: Path = None) -> Dict[str, List[str]]:
    """
    Load SIGNAL_TEMPLATES from JSON file.
    
    Args:
        templates_file: Path to signal_templates.json (default: data/signal_templates.json)
        
    Returns:
        Dict mapping category to list of template strings
    """
    global _loaded_templates
    
    if _loaded_templates is not None:
        return _loaded_templates
    
    if templates_file is None:
        templates_file = PROJECT_ROOT / "data" / "signal_templates.json"
    
    if templates_file.exists():
        try:
            with open(templates_file, 'r', encoding='utf-8') as f:
                loaded = json.load(f)
            logger.info(f"✓ Loaded signal templates from {templates_file}")
            
            # Filter out empty categories
            _loaded_templates = {k: v for k, v in loaded.items() if v}
            return _loaded_templates
        except Exception as e:
            logger.warning(f"Failed to load templates from {templates_file}: {e}")
    else:
        logger.info(f"Templates file not found: {templates_file}. Using hardcoded defaults.")
    
    # Fallback to hardcoded
    _loaded_templates = SIGNAL_TEMPLATES
    return _loaded_templates


def load_tag_keywords(keywords_file: Path = None) -> Dict[str, Dict[str, str]]:
    """
    Load TAG_KEYWORDS from JSON file.
    
    Args:
        keywords_file: Path to tag_keywords.json (default: data/tag_keywords.json)
        
    Returns:
        Dict mapping category to dict of {keyword: tag}
    """
    global _loaded_keywords
    
    if _loaded_keywords is not None:
        return _loaded_keywords
    
    if keywords_file is None:
        keywords_file = PROJECT_ROOT / "data" / "tag_keywords.json"
    
    if keywords_file.exists():
        try:
            with open(keywords_file, 'r', encoding='utf-8') as f:
                loaded = json.load(f)
            logger.info(f"✓ Loaded tag keywords from {keywords_file}")
            
            # Filter out empty categories
            _loaded_keywords = {k: v for k, v in loaded.items() if v}
            return _loaded_keywords
        except Exception as e:
            logger.warning(f"Failed to load keywords from {keywords_file}: {e}")
    else:
        logger.info(f"Keywords file not found: {keywords_file}. Using hardcoded defaults.")
    
    # Fallback to hardcoded TAG_KEYWORDS (defined at bottom of file)
    _loaded_keywords = TAG_KEYWORDS
    return _loaded_keywords


def get_embedding_model(model_name: str = "KBLab/sentence-bert-swedish-cased") -> SentenceTransformer:
    """
    Load and cache the Swedish sentence transformer model.
    
    Args:
        model_name: HuggingFace model identifier
        
    Returns:
        SentenceTransformer model
    """
    global _model
    
    if _model is None:
        logger.info(f"Loading Swedish embedding model: {model_name}")
        try:
            _model = SentenceTransformer(model_name)
            logger.info("✓ Embedding model loaded")
        except Exception as e:
            logger.error(f"Failed to load embedding model: {e}")
            raise
    
    return _model


def get_signal_embeddings(
    model: SentenceTransformer = None,
    templates: Dict[str, List[str]] = None,
) -> Dict[str, np.ndarray]:
    """
    Pre-compute embeddings for all signal templates.
    
    Args:
        model: SentenceTransformer model
        templates: Dict mapping signal category to list of semantic templates (loads from JSON if None)
        
    Returns:
        Dict mapping category to array of template embeddings (not averaged)
    """
    global _signal_embeddings
    
    if _signal_embeddings is not None:
        return _signal_embeddings
    
    if model is None:
        model = get_embedding_model()
    
    if templates is None:
        templates = load_signal_templates()
    
    logger.info("Computing signal embeddings from templates...")
    _signal_embeddings = {}
    
    for category, category_templates in templates.items():
        if not category_templates:  # Skip empty categories
            continue
            
        # Encode all templates for this category
        embeddings = model.encode(category_templates, convert_to_numpy=True)
        
        # Store all template embeddings (will use max/top-k similarity later)
        _signal_embeddings[category] = embeddings
        
        logger.debug(f"  {category:20s}: stored {len(category_templates)} template embeddings")
    
    return _signal_embeddings


def classify_article_embedding(
    title: str,
    description: str = "",
    similarity_threshold: float = 0.35,
    model: SentenceTransformer = None,
    signal_embeddings: Dict[str, np.ndarray] = None,
    top_k_signals: int = None,
    relative_threshold: float = 0.70,
    preprocess: bool = True,
    extract_keywords: bool = False,
) -> Dict[str, Tuple[float, str]]:
    """
    Classify article using embedding-based semantic similarity.
    
    Instead of keyword matching, this computes embeddings for the article
    and compares them to semantic templates for each signal category.
    Similarity scores are directly used as confidence scores.
    
    Args:
        title: Article title
        description: Article description/body
        similarity_threshold: Base similarity threshold (minimum to consider)
        model: SentenceTransformer model (uses cached if None)
        signal_embeddings: Pre-computed signal embeddings (uses cached if None)
        top_k_signals: If set, only return top K most confident signals (default: None = all above threshold)
        relative_threshold: Only keep signals within this ratio of max similarity (default: 0.70)
            e.g., if max_sim=0.9, only keep signals with sim >= 0.9 * 0.70 = 0.63
        preprocess: If True, preprocess Swedish text (remove stopwords, stem, remove punctuation)
        extract_keywords: If True, extract keywords from preprocessed text (requires preprocess=True)
        
    Returns:
        Dict mapping category to (score, tag) tuple
        e.g., {"emergencies": (0.72, "fire"), "crime": (0.41, "police")}
    """
    if model is None:
        model = get_embedding_model()
    
    if signal_embeddings is None:
        signal_embeddings = get_signal_embeddings(model)
    
    # Combine title and description for better semantic context
    combined_text = f"{title} {description}".strip()
    
    if not combined_text:
        return {}
    
    # Preprocess if requested
    if preprocess:
        combined_text = preprocess_swedish_text(combined_text, remove_stopwords=True, stem=True)
        logger.debug(f"Preprocessed text: {combined_text[:100]}...")
    
    # Extract keywords if requested
    keywords_dict = {}
    if extract_keywords and preprocess:
        keywords_dict = extract_keywords_with_encoder(combined_text, max_keywords=30)
        logger.debug(f"Extracted keywords: {list(keywords_dict.keys())[:10]}")
    
    # Encode the article
    article_embedding = model.encode(combined_text, convert_to_numpy=True)
    
    # Compute cosine similarity to each signal category
    results = {}
    all_scores = []  # Track all scores for relative filtering

    for category, template_embeddings in signal_embeddings.items():
        # Skip if no embeddings for this category
        if template_embeddings is None or len(template_embeddings) == 0:
            continue
            
        # Compute similarity to each template in this category
        similarities = []
        for template_emb in template_embeddings:
            # Cosine similarity: (A·B) / (|A||B|)
            similarity = np.dot(article_embedding, template_emb) / (
                np.linalg.norm(article_embedding) * np.linalg.norm(template_emb)
            )
            similarities.append(similarity)
        
        # Use max similarity (best match across all templates in category)
        max_similarity = max(similarities)
        confidence_score = max(0.0, max_similarity)
        
        # Also track which template matched best for tag inference
        best_template_idx = np.argmax(similarities)

        if confidence_score >= similarity_threshold:
            # Select tag based on the best-matching template
            # Use loaded templates with fallback to hardcoded SIGNAL_TEMPLATES
            templates = load_signal_templates()
            category_templates = templates.get(category, [])
            if best_template_idx < len(category_templates):
                best_template = category_templates[best_template_idx]
            else:
                # Fallback if index out of range
                best_template = category_templates[0] if category_templates else ""
            
            # Infer tag from best template
            tag = infer_tag_from_template(category, best_template)
            
            results[category] = (confidence_score, tag)
            all_scores.append(confidence_score)
    
    # Filter to keep only high-confidence signals
    if results and (top_k_signals or relative_threshold) and all_scores:
        max_score = max(all_scores)
        
        # Apply relative threshold: keep signals within X% of the max
        if relative_threshold and max_score > 0:
            min_relative_score = max_score * relative_threshold
            results = {
                cat: (score, tag) 
                for cat, (score, tag) in results.items() 
                if score >= min_relative_score
            }
        
        # Apply top-K filtering if specified
        if top_k_signals and len(results) > top_k_signals:
            sorted_results = sorted(results.items(), key=lambda x: x[1][0], reverse=True)
            # Safely slice with bounds checking
            k = min(top_k_signals, len(sorted_results))
            results = dict(sorted_results[:k])
    
    return results


def infer_tag_from_template(category: str, template: str) -> str:
    """
    Infer a tag value based on the best-matching template for a category.
    
    This is a simple heuristic that extracts key signal words from templates.
    
    Args:
        category: Signal category
        template: The best-matching template text
        
    Returns:
        Tag string (empty if no specific tag detected)
    """
    template_lower = template.lower()
    
    # Load tag keywords from JSON or use hardcoded defaults
    tag_keywords_dict = load_tag_keywords()
    
    # Check for keywords specific to this category
    if category in tag_keywords_dict:
        for keyword, tag in tag_keywords_dict[category].items():
            if keyword in template_lower:
                return tag
    
    # Fallback to empty tag if no match
    return ""


# Hardcoded TAG_KEYWORDS as fallback (will be replaced by JSON if available)
TAG_KEYWORDS = {
    "emergencies": {
        "brand": "fire",
        "fire": "fire",
        "explosion": "explosion",
        "earthquake": "earthquake",
        "evacuation": "evacuation",
        "olycka": "accident",
        "flood": "flood",
        "storm": "storm",
    },
    "crime": {
        "rån": "robbery",
        "stöld": "theft",
        "misshandling": "assault",
        "mord": "assault",
        "inbrott": "theft",
        "polis": "police",
        "robbery": "robbery",
        "burglary": "theft",
        "assault": "assault",
        "vandalism": "vandalism",
    },
        "festivals": {
            "konsert": "concert",
            "firande": "celebration",
            "fest": "celebration",
            "mästerskap": "event",
            "concert": "concert",
            "festival": "event",
            "parade": "celebration",
        },
        "transportation": {
            "trafik": "traffic",
            "trafikolycka": "accident",
            "kö": "congestion",
            "stängd": "closure",
            "vägen": "closure",
            "traffic": "traffic",
            "accident": "accident",
            "delay": "delay",
            "closure": "closure",
            "cancelled": "delay",
        },
        "weather_temp": {
            "varme": "hot",
            "hettan": "hot",
            "kylan": "cold",
            "frysande": "cold",
            "temperatur": "hot",
            "heat": "hot",
            "heatwave": "hot",
            "cold": "cold",
        },
        "weather_wet": {
            "regn": "rain",
            "snö": "snow",
            "översvämning": "flood",
            "skyfall": "rain",
            "blöt": "rain",
            "storm": "rain",
            "rain": "rain",
            "snow": "snow",
            "flood": "flood",
            "hail": "rain",
        },
        "sports": {
            "fotboll": "football",
            "hockey": "hockey",
            "seger": "victory",
            "vinna": "victory",
            "match": "football",
            "tävl": "event",
            "football": "football",
            "hockey": "hockey",
            "victory": "victory",
            "championship": "championship",
        },
        "economics": {
            "börsen": "market",
            "marknad": "market",
            "arbetslöshet": "employment",
            "företag": "business",
            "inflation": "inflation",
            "handel": "trade",
            "market": "market",
            "inflation": "inflation",
            "unemployment": "employment",
            "growth": "growth",
            "recession": "inflation",
        },
        "politics": {
            "val": "election",
            "protest": "protest",
            "regering": "government",
            "parlament": "government",
            "lag": "policy",
            "politiker": "government",
            "election": "election",
            "protest": "protest",
            "government": "government",
            "parliament": "government",
            "strike": "protest",
        },
    }


# For backwards compatibility, wrap this in classify_article if needed
def classify_article_with_fallback(
    title: str,
    description: str = "",
    use_embedding: bool = True,
) -> Dict[str, Tuple[float, str]]:
    """
    Classify article, trying embedding-based first, then keyword fallback.
    
    Args:
        title: Article title
        description: Article description
        use_embedding: If True, use embedding-based; otherwise use keywords only
        
    Returns:
        Dict mapping category to (score, tag) tuple
    """
    if use_embedding:
        try:
            result = classify_article_embedding(title, description)
            if result:
                logger.debug(f"Embedding classification succeeded: {result}")
                return result
        except Exception as e:
            logger.warning(f"Embedding classification failed: {e}")
    
    # Fallback to keyword-based
    from ml.ingestion.hopsworks_pipeline import classify_article as keyword_classify
    return keyword_classify(title, description)
